services:
  connect:
    privileged: true
    image: rstudio/rstudio-connect:ubuntu2204-2024.05.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3939/"]
      start_period: 30s
      start_interval: 1s
    volumes:
      - ./.cache/data:/data
      - ./__tests__/rstudio-connect.test.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg
    ports:
      - 23939:3939
    environment:
      RSC_LICENSE: $RSC_LICENSE
