services:
  db:
    image: postgres:12
    volumes:
      - ./.cache/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: notasecret
  connect:
    privileged: true
    depends_on:
      - db
    image: rstudio/rstudio-connect:ubuntu2204-2024.05.0
    volumes:
      - ./.cache/data:/data
      - ./__tests__/rstudio-connect.test.gcfg:/etc/rstudio-connect/rstudio-connect.gcfg
    ports:
      - 23939:3939
    environment:
      RSC_LICENSE: $RSC_LICENSE
